### ISSUE TITLE
ios loading 没能关闭

### ISSUE THREAD

**Issue by zhmeng** [Yenole/react-native-easy-loading#1]
你好，我的 react native 用了这个插件，可以显示Loading效果，调用 dismiss Loading依然存在. 不知道是不是为什么呢？
调用 fetch 之前进行了 Loading show ．fetch complete 后　Loading dimiss ．同时这个时候自己用了Alert,有Alert Loading 就不能正常关闭了．
android　没有问题

**Comment by RoJoHub** [comment]
同样的问题

**Comment by aacxg** [comment]
同样的问题

**Comment by tangyongjing** [comment]
我也是这个问题，能解决吗？

**Comment by zouyu0008** [comment]
代码呢？
一般很多是 EasyLoading.dismis(这里没加相同类型);
